"""consulting.prompts — Single source of truth for consulting module prompts.

All prompt templates, disclaimer text, and builder functions for the
consulting RAG pipeline are defined here.  NO other consulting file
should hardcode prompt strings — import from this module instead.

Groups:
    - DISCLAIMER          → bilingual legal disclaimer (auto-appended)
    - NO_RETRIEVAL        → fallback when KB returns 0 chunks
    - SYSTEM_PROMPT       → persona system prompt builder (language override)
"""

from __future__ import annotations


# ============================================================
# Disclaimer — auto-appended to every consulting response
# ============================================================

DISCLAIMER: dict[str, str] = {
    "zh": (
        "\n\n---\n"
        "⚠️ **免责声明**：以上回答由 AI 顾问基于知识库生成，仅供参考，不构成法律、"
        "移民、医疗或财务等专业建议。重要决策请咨询持牌专业人士。"
    ),
    "en": (
        "\n\n---\n"
        "⚠️ **Disclaimer**: This response is generated by an AI advisor based on its "
        "knowledge base and is for informational purposes only. It does not constitute "
        "legal, immigration, medical, or financial advice. Please consult a licensed "
        "professional for important decisions."
    ),
}

# Keywords used to detect if a disclaimer is already present in the answer
DISCLAIMER_MARKERS: tuple[str, ...] = ("免责声明", "Disclaimer", "disclaimer")


# ============================================================
# No-retrieval fallback — when KB returns 0 relevant chunks
# ============================================================

NO_RETRIEVAL_TEMPLATE: str = (
    'The user asked: "{question}"\n\n'
    'You are the "{persona_name}" advisor. '
    "Your knowledge base did NOT return any relevant documents for this query. "
    "Politely tell the user that you couldn't find relevant information in "
    "your current knowledge base. Suggest they try rephrasing their question "
    "or that the topic may not yet be covered. "
    "Keep your reply concise (3-5 sentences). "
    "Reply in English."
)


def build_no_retrieval_prompt(question: str, persona_name: str) -> str:
    """Build the no-retrieval fallback user-message from template."""
    return NO_RETRIEVAL_TEMPLATE.format(question=question, persona_name=persona_name)


# ============================================================
# Small-talk / greeting — respond naturally without RAG
# ============================================================

SMALL_TALK_TEMPLATE: str = (
    'The user said: "{question}"\n\n'
    'You are the "{persona_name}" advisor. '
    "This is a casual greeting or small-talk message — NOT a domain question. "
    "Respond warmly and naturally as yourself. "
    "Briefly introduce what you can help with (studying or immigrating to Canada). "
    "Do NOT mention knowledge bases, documents, retrieval, or that you couldn't find information. "
    "Keep your reply short (1-3 sentences). "
    "Reply in the same language the user used."
)


def build_small_talk_prompt(question: str, persona_name: str) -> str:
    """Build user-message for small-talk / greeting responses."""
    return SMALL_TALK_TEMPLATE.format(question=question, persona_name=persona_name)


# ============================================================
# Language utilities
# ============================================================

LANGUAGE_NAMES: dict[str, str] = {
    "en": "English",
    "fr": "Français",
    "es": "Español",
    "zh": "中文",
}


def detect_language(text: str) -> str:
    """Heuristic: if ≥30% of non-whitespace chars are CJK, return 'zh', else 'en'."""
    cjk = sum(1 for ch in text if "\u4e00" <= ch <= "\u9fff")
    total = max(len(text.replace(" ", "")), 1)
    return "zh" if (cjk / total) >= 0.3 else "en"


# ============================================================
# Disclaimer helpers
# ============================================================

def get_disclaimer(lang: str) -> str:
    """Get disclaimer text for a language code.  Falls back to English."""
    return DISCLAIMER.get(lang, DISCLAIMER["en"])


def append_disclaimer(answer: str, question: str) -> str:
    """Append disclaimer if not already present.  Always in English per user request."""
    if any(marker in answer for marker in DISCLAIMER_MARKERS):
        return answer  # already has disclaimer
    # Always use English disclaimer — user explicitly requested it not be translated
    return answer + get_disclaimer("en")


# ============================================================
# System prompt builder — persona prompt + language override
# ============================================================

def build_system_prompt(persona: dict, response_language: str | None = None) -> str:
    """Build final system prompt from persona config + optional language override.

    Args:
        persona: Persona dict from Payload CMS (must have 'systemPrompt' key).
        response_language: Optional ISO 639-1 code for response language override.
            When set, appends a language instruction to the system prompt.

    Returns:
        Complete system prompt string.
    """
    system_prompt = persona.get("systemPrompt", "")

    # Universal: prevent LLM from generating its own disclaimer —
    # the system auto-appends a standardised one via append_disclaimer().
    system_prompt += (
        "\n\nIMPORTANT: Do NOT add any disclaimers, verification notices, "
        "or 'consult a professional' warnings at the end of your response. "
        "The system appends one automatically."
    )

    # Universal: require inline source citations for traceability.
    system_prompt += (
        "\n\nCITATION RULE: You MUST cite sources inline using [N] bracket format. "
        "Every factual claim must reference at least one source, e.g. "
        "'Students can work up to 20 hours per week [1].' "
        "If multiple sources support a claim, list them: [1] [3]. "
        "Never use parenthetical formats like (Source 1) or (Sources 1, 3) — "
        "always use square brackets [N]. "
        "Never make a factual statement without a source citation."
    )

    # Default: always respond in English (knowledge base is English)
    if response_language:
        lang_name = LANGUAGE_NAMES.get(response_language, response_language)
        system_prompt += f"\n\nPlease respond in {lang_name}."
    else:
        system_prompt += "\n\nPlease respond in English."
    return system_prompt

