"""consulting.prompts — Single source of truth for consulting module prompts.

All prompt templates, disclaimer text, and builder functions for the
consulting RAG pipeline are defined here.  NO other consulting file
should hardcode prompt strings — import from this module instead.

Groups:
    - DISCLAIMER          → bilingual legal disclaimer (auto-appended)
    - NO_RETRIEVAL        → fallback when KB returns 0 chunks
    - SYSTEM_PROMPT       → persona system prompt builder (language override)
"""

from __future__ import annotations


# ============================================================
# Disclaimer — auto-appended to every consulting response
# ============================================================

DISCLAIMER: dict[str, str] = {
    "zh": (
        "\n\n---\n"
        "⚠️ **免责声明**：以上回答由 AI 顾问基于知识库生成，仅供参考，不构成法律、"
        "移民、医疗或财务等专业建议。重要决策请咨询持牌专业人士。"
    ),
    "en": (
        "\n\n---\n"
        "⚠️ **Disclaimer**: This response is generated by an AI advisor based on its "
        "knowledge base and is for informational purposes only. It does not constitute "
        "legal, immigration, medical, or financial advice. Please consult a licensed "
        "professional for important decisions."
    ),
}

# Keywords used to detect if a disclaimer is already present in the answer
DISCLAIMER_MARKERS: tuple[str, ...] = ("免责声明", "Disclaimer", "disclaimer")


# ============================================================
# No-retrieval fallback — when KB returns 0 relevant chunks
# ============================================================

NO_RETRIEVAL_TEMPLATE: str = (
    'The user asked: "{question}"\n\n'
    'You are the "{persona_name}" advisor. '
    "Your knowledge base did NOT return any relevant documents for this query. "
    "Politely tell the user that you couldn't find relevant information in "
    "your current knowledge base. Suggest they try rephrasing their question "
    "or that the topic may not yet be covered. "
    "Keep your reply concise (3-5 sentences). "
    "Reply in the SAME LANGUAGE the user used in their question."
)


def build_no_retrieval_prompt(question: str, persona_name: str) -> str:
    """Build the no-retrieval fallback user-message from template."""
    return NO_RETRIEVAL_TEMPLATE.format(question=question, persona_name=persona_name)


# ============================================================
# Language utilities
# ============================================================

LANGUAGE_NAMES: dict[str, str] = {
    "en": "English",
    "fr": "Français",
    "es": "Español",
    "zh": "中文",
}


def detect_language(text: str) -> str:
    """Heuristic: if ≥30% of non-whitespace chars are CJK, return 'zh', else 'en'."""
    cjk = sum(1 for ch in text if "\u4e00" <= ch <= "\u9fff")
    total = max(len(text.replace(" ", "")), 1)
    return "zh" if (cjk / total) >= 0.3 else "en"


# ============================================================
# Disclaimer helpers
# ============================================================

def get_disclaimer(lang: str) -> str:
    """Get disclaimer text for a language code.  Falls back to English."""
    return DISCLAIMER.get(lang, DISCLAIMER["en"])


def append_disclaimer(answer: str, question: str) -> str:
    """Append disclaimer if not already present.  Language matches the question."""
    if any(marker in answer for marker in DISCLAIMER_MARKERS):
        return answer  # already has disclaimer
    lang = detect_language(question)
    return answer + get_disclaimer(lang)


# ============================================================
# System prompt builder — persona prompt + language override
# ============================================================

def build_system_prompt(persona: dict, response_language: str | None = None) -> str:
    """Build final system prompt from persona config + optional language override.

    Args:
        persona: Persona dict from Payload CMS (must have 'systemPrompt' key).
        response_language: Optional ISO 639-1 code for response language override.
            When set (and not 'zh' which is the default), appends a language
            instruction to the system prompt.

    Returns:
        Complete system prompt string.
    """
    system_prompt = persona.get("systemPrompt", "")
    if response_language and response_language != "zh":
        lang_name = LANGUAGE_NAMES.get(response_language, response_language)
        system_prompt += f"\n\nPlease respond in {lang_name}."
    return system_prompt
