/**
 * seed/data-sources.ts — Pre-configured data sources for Ottawa EcDev.
 *
 * Sources extracted from docs/project-brief.md Section 3.
 * Categories: city, real_estate, tourism, commercial, research, news
 */

export const dataSourcesData: Record<string, unknown>[] = [
  {
    name: 'City of Ottawa - ED Updates',
    shortName: 'ED Updates',
    category: 'city',
    discoveryUrl: 'https://ottawa.ca/en/planning-development-and-construction/housing-and-development-reports/local-economic-development-information/economic-development-update',
    type: 'url_pattern',
    pdfPattern: 'economic_update.*\\.pdf$',
    schedule: 'quarterly',
    icon: '🏛️',
    enabled: true,
    description: 'Quarterly Economic Development Update reports (Q1 2022 – Q4 2025). Primary data source for Ottawa economic indicators.',
    docsFound: 0,
    docsIngested: 0,
  },
  {
    name: 'Ottawa Real Estate Board',
    shortName: 'OREB',
    category: 'real_estate',
    discoveryUrl: 'https://www.oreb.ca/newsroom/news-releases/',
    type: 'pdf_crawl',
    pdfPattern: 'MarketUpdate.*\\.pdf$',
    schedule: 'monthly',
    icon: '🏠',
    enabled: true,
    description: 'Monthly MLS® market update reports with resale statistics, average prices, and sales volumes.',
    docsFound: 0,
    docsIngested: 0,
  },
  {
    name: 'Canada Mortgage & Housing Corporation',
    shortName: 'CMHC',
    category: 'real_estate',
    discoveryUrl: 'https://www.cmhc-schl.gc.ca/professionals/housing-markets-data-and-research/market-reports/housing-market',
    type: 'pdf_crawl',
    pdfPattern: '\\.pdf$',
    schedule: 'quarterly',
    icon: '🏗️',
    enabled: false,
    description: 'Housing market reports including starts, completions, and rental market data for the Ottawa-Gatineau CMA.',
    docsFound: 0,
    docsIngested: 0,
  },
  {
    name: 'Invest Ottawa',
    shortName: 'Invest Ottawa',
    category: 'news',
    discoveryUrl: 'https://www.investottawa.ca/',
    type: 'pdf_crawl',
    pdfPattern: '\\.pdf$',
    schedule: 'monthly',
    icon: '💼',
    enabled: false,
    description: 'Lead Economic Development Agency — research reports, market assessments, and industry analysis.',
    docsFound: 0,
    docsIngested: 0,
  },
  {
    name: 'Colliers Ottawa',
    shortName: 'Colliers',
    category: 'commercial',
    discoveryUrl: 'https://www.colliers.com/en-ca/cities/ottawa',
    type: 'pdf_crawl',
    pdfPattern: '\\.pdf$',
    schedule: 'quarterly',
    icon: '🏢',
    enabled: false,
    description: 'Commercial real estate market reports — office, retail, and industrial vacancy rates for Ottawa.',
    docsFound: 0,
    docsIngested: 0,
  },
  {
    name: 'Statistics Canada',
    shortName: 'StatsCan',
    category: 'research',
    discoveryUrl: 'https://www.statcan.gc.ca',
    type: 'api',
    schedule: 'monthly',
    icon: '📊',
    enabled: false,
    description: 'Federal statistical data — labour force, CPI, GDP, and population indicators. API integration (Phase 2).',
    docsFound: 0,
    docsIngested: 0,
  },
  {
    name: 'Ottawa Tourism',
    shortName: 'Ottawa Tourism',
    category: 'tourism',
    discoveryUrl: 'https://www.ottawatourism.ca/',
    type: 'pdf_crawl',
    schedule: 'quarterly',
    icon: '✈️',
    enabled: false,
    description: 'Tourism economic impact reports, visitor statistics, and annual tourism contribution data.',
    docsFound: 0,
    docsIngested: 0,
  },
]
