/**
 * data-sources-persona/education.ts — Data sources for 5 education personas.
 */
import type { PersonaDataSource } from './types'

export const educationSources: PersonaDataSource[] = [
  // ── edu-school-planning (3) ───────────────────────────────
  {
    nameEn: 'IRCC Designated Learning Institutions List',
    nameZh: 'IRCC 指定学习机构列表',
    description: 'Official list of DLI-designated schools eligible to enroll international students.',
    discoveryUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/prepare/designated-learning-institutions-list.html',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'edu-school-planning',
  },
  {
    nameEn: 'OUAC Ontario University Application Guide',
    nameZh: 'OUAC 安省大学申请指南',
    description: 'Ontario Universities Application Centre — application process and deadlines.',
    discoveryUrl: 'https://www.ouac.on.ca/guide/',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'edu-school-planning',
  },
  {
    nameEn: 'EduCanada Study in Canada',
    nameZh: 'EduCanada 留学加拿大指南',
    description: 'Government of Canada official study guide for international students.',
    discoveryUrl: 'https://www.educanada.ca/study-plan-etudes/index.aspx?lang=eng',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'edu-school-planning',
  },
  // ── edu-visa-compliance (2) ───────────────────────────────
  {
    nameEn: 'IRCC Study Permit Application',
    nameZh: 'IRCC 学签申请指南',
    description: 'Official study permit application requirements and eligibility.',
    discoveryUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'weekly',
    _personaSlug: 'edu-visa-compliance',
  },
  {
    nameEn: 'IRCC Extend Study Permit',
    nameZh: 'IRCC 学签续签',
    description: 'How to extend or change conditions on a study permit.',
    discoveryUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/extend-study-permit.html',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'weekly',
    _personaSlug: 'edu-visa-compliance',
  },
  // ── edu-academic-rules (2) ────────────────────────────────
  {
    nameEn: 'Ontario Universities Info',
    nameZh: '安省大学联合会',
    description: 'Council of Ontario Universities — academic policies and standards.',
    discoveryUrl: 'https://ontariouniversities.ca/',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'edu-academic-rules',
  },
  {
    nameEn: 'Ontario Colleges',
    nameZh: '安省学院申请中心',
    description: 'Ontario Colleges application portal — programs, requirements, deadlines.',
    discoveryUrl: 'https://www.ontariocolleges.ca/en',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'edu-academic-rules',
  },
  // ── edu-work-permit (2) ───────────────────────────────────
  {
    nameEn: 'IRCC Post-Graduation Work Permit',
    nameZh: 'IRCC 毕业后工签 (PGWP)',
    description: 'Post-Graduation Work Permit program eligibility and application.',
    discoveryUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/after-graduation.html',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'weekly',
    _personaSlug: 'edu-work-permit',
  },
  {
    nameEn: 'IRCC Work While Studying',
    nameZh: 'IRCC 留学期间打工规定',
    description: 'Rules for working while studying in Canada on a study permit.',
    discoveryUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work.html',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'weekly',
    _personaSlug: 'edu-work-permit',
  },
  // ── edu-child-education (2) ───────────────────────────────
  {
    nameEn: 'Ontario School System K-12',
    nameZh: '安省 K-12 公立教育体系',
    description: 'Ontario public school system overview — kindergarten through grade 12.',
    discoveryUrl: 'https://www.ontario.ca/page/ontario-schools-kindergarten-grade-12',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'edu-child-education',
  },
  {
    nameEn: 'Ontario Child Care Options',
    nameZh: '安省托儿和幼教选择',
    description: 'Licensed child care and early learning options in Ontario.',
    discoveryUrl: 'https://www.ontario.ca/page/child-care-options',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'edu-child-education',
  },
]
