/**
 * data-sources-persona/settlement.ts — Data sources for 5 settlement personas.
 */
import type { PersonaDataSource } from './types'

export const settlementSources: PersonaDataSource[] = [
  // ── life-rental (3) ───────────────────────────────────────
  {
    nameEn: 'Ontario Residential Tenancies Act',
    nameZh: '安省住宅租赁法 (RTA)',
    description: 'Full text of the Residential Tenancies Act — tenant and landlord rights.',
    discoveryUrl: 'https://www.ontario.ca/laws/statute/06r17',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-rental',
  },
  {
    nameEn: 'Ontario Standard Lease Guide',
    nameZh: '安省标准租约指南',
    description: 'Guide to the Ontario Standard Lease agreement.',
    discoveryUrl: 'https://www.ontario.ca/page/guide-ontarios-standard-lease',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-rental',
  },
  {
    nameEn: 'Landlord and Tenant Board',
    nameZh: '房东租客委员会 (LTB)',
    description: 'LTB dispute resolution, applications, and tenant rights.',
    discoveryUrl: 'https://tribunalsontario.ca/ltb/',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-rental',
  },
  // ── life-driving (2) ──────────────────────────────────────
  {
    nameEn: 'Ontario DriveTest',
    nameZh: '安省驾照考试中心 (DriveTest)',
    description: 'Ontario driver testing — locations, booking, and test preparation.',
    discoveryUrl: 'https://drivetest.ca/',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-driving',
  },
  {
    nameEn: 'Ontario G Licence for New Drivers',
    nameZh: '安省新手 G 驾照流程',
    description: 'MTO graduated licensing system — G1, G2, G requirements.',
    discoveryUrl: 'https://www.ontario.ca/page/get-g-drivers-licence-new-drivers',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-driving',
  },
  // ── life-utilities (2) ────────────────────────────────────
  {
    nameEn: 'Toronto Hydro Rates',
    nameZh: '多伦多电力费率 (Toronto Hydro)',
    description: 'Electricity rates, time-of-use pricing, and billing information.',
    discoveryUrl: 'https://www.torontohydro.com/for-home/rates-and-billing',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-utilities',
  },
  {
    nameEn: 'Ontario Energy Board Consumer Info',
    nameZh: '安省能源委员会消费者须知 (OEB)',
    description: 'Ontario Energy Board — consumer rights and energy pricing.',
    discoveryUrl: 'https://www.oeb.ca/consumer-information-and-protection',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-utilities',
  },
  // ── life-home-buying (2) ──────────────────────────────────
  {
    nameEn: 'CMHC Home Buying Guide',
    nameZh: 'CMHC 购房指南',
    description: 'CMHC guide to buying a home in Canada — first-time buyer programs.',
    discoveryUrl: 'https://www.cmhc-schl.gc.ca/consumers/home-buying',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-home-buying',
  },
  {
    nameEn: 'Ontario Land Transfer Tax',
    nameZh: '安省土地转让税',
    description: 'Ontario land transfer tax rates and first-time buyer rebate.',
    discoveryUrl: 'https://www.ontario.ca/page/land-transfer-tax',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-home-buying',
  },
  // ── life-car (2) ──────────────────────────────────────────
  {
    nameEn: 'Ontario Buy or Sell Used Vehicle',
    nameZh: '安省买卖二手车指南',
    description: 'Steps to buy or sell a used vehicle in Ontario — registration and safety.',
    discoveryUrl: 'https://www.ontario.ca/page/buy-or-sell-used-vehicle-ontario',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-car',
  },
  {
    nameEn: 'Ontario Vehicle Registration',
    nameZh: '安省车辆注册和牌照',
    description: 'How to register a vehicle and get licence plates in Ontario.',
    discoveryUrl: 'https://www.ontario.ca/page/register-vehicle-permit',
    type: 'web_scrape',
    enabled: true,
    autoSync: true,
    syncInterval: 'monthly',
    _personaSlug: 'life-car',
  },
]
