import type { CollectionConfig } from 'payload'

/**
 * Questions — stores AI-generated and user-submitted study questions.
 *
 * Fields:
 *   - question: the question text
 *   - bookId: engine text book_id (e.g. "bishop_prml")
 *   - bookTitle: denormalized for display
 *   - topicHint: short topic label
 *   - source: 'ai' | 'manual'
 *   - likes: thumbs-up counter
 *   - category: derived from book category for sidebar filtering
 *   - subcategory: derived from book subcategory
 */
export const Questions: CollectionConfig = {
  slug: 'questions',
  admin: {
    useAsTitle: 'question',
    defaultColumns: ['question', 'bookTitle', 'topicHint', 'likes', 'source', 'createdAt'],
    group: 'Content',
  },
  access: {
    read: () => true,
    create: () => true,     // anyone can create (questions are generated by AI or submitted)
    update: () => true,     // allow like updates
    delete: ({ req }) => Boolean(req.user),
  },
  fields: [
    {
      name: 'question',
      type: 'textarea',
      required: true,
      admin: { description: 'The study question text' },
    },
    {
      name: 'bookId',
      type: 'text',
      required: true,
      admin: { description: 'Engine book_id (e.g. "bishop_prml")' },
    },
    {
      name: 'bookTitle',
      type: 'text',
      admin: { description: 'Book title for display' },
    },
    {
      name: 'topicHint',
      type: 'text',
      admin: { description: 'Short topic label (e.g. "BM25", "Chapter 3")' },
    },
    {
      name: 'source',
      type: 'select',
      defaultValue: 'ai',
      options: [
        { label: 'AI Generated', value: 'ai' },
        { label: 'User Submitted', value: 'manual' },
      ],
    },
    {
      name: 'likes',
      type: 'number',
      defaultValue: 0,
      min: 0,
      admin: { description: 'Thumbs-up count' },
    },
    {
      name: 'category',
      type: 'text',
      admin: { description: 'Book category for filtering' },
    },
    {
      name: 'subcategory',
      type: 'text',
      admin: { description: 'Book subcategory for filtering' },
    },
  ],
}
