"""Shared data types for the RAG Core layer."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ChunkHit:
    """A single retrieved chunk with scoring metadata."""

    # Core fields (always present)
    id: int
    chunk_id: str
    book_id: int
    text: str
    content_type: str = "text"
    reading_order: int = 0

    # Metadata (populated by _enrich_metadata)
    book_title: str = ""
    chapter_title: str | None = None
    primary_page_number: int | None = None
    category: str = "textbook"
    source_locators: list[dict] = field(default_factory=list)
    chroma_document_id: str | None = None

    # Per-strategy ranking signals (set by each strategy)
    fts_rank: int | None = None
    fts_score: float | None = None
    vec_rank: int | None = None
    vec_distance: float | None = None
    toc_rank: int | None = None
    toc_score: float | None = None
    pageindex_rank: int | None = None
    pageindex_score: float | None = None

    # RRF fusion (set by RRFusion)
    rrf_score: float | None = None
    fused_rank: int | None = None


@dataclass
class StrategyResult:
    """Results from a single retrieval strategy."""

    strategy: str          # e.g. "fts5_bm25"
    hits: list[ChunkHit]
    query_used: str = ""   # actual query string sent to strategy (for trace)
    error: str | None = None


@dataclass
class RetrievalResult:
    """Aggregated retrieval result from all enabled strategies."""

    chunks: list[ChunkHit]                       # final top_k fused chunks
    per_strategy: dict[str, StrategyResult]      # raw per-strategy results
    stats: dict[str, int] = field(default_factory=dict)


@dataclass
class CitationResult:
    """Result of citation validation and sanitization."""

    cleaned_answer: str
    raw_answer: str
    valid_citations: list[int]
    invalid_citations: list[int]
    sources: list[dict]   # list[SourceInfo-like dicts]


@dataclass
class QualityWarning:
    """A quality warning generated by QualityChecker."""

    level: str   # "warn" | "error"
    code: str    # e.g. "NO_FTS_HITS"
    message: str
    suggestion: str = ""


@dataclass
class RAGResponse:
    """Full response from RAGCore.query()."""

    answer: str
    sources: list[dict]
    trace: dict
    warnings: list[QualityWarning]
    stats: dict[str, int]
