import type { CollectionConfig } from 'payload'
import { isEditorOrAdmin } from '../access/isEditorOrAdmin'

/**
 * Questions — stores AI-generated and user-submitted study questions.
 *
 * Fields:
 *   - question: the question text
 *   - bookId: engine text book_id (e.g. "bishop_prml")
 *   - bookTitle: denormalized for display
 *   - topicHint: short topic label
 *   - source: 'ai' | 'manual'
 *   - likes: thumbs-up counter
 *   - category: derived from book category for sidebar filtering
 *   - subcategory: derived from book subcategory
 *   - sourceChunkId: chunk node ID the question was generated from (QD-01)
 *   - referenceAnswer: LLM-generated reference answer (QD-01)
 *   - datasetId: relationship to QuestionSets collection (QD-01)
 */
export const Questions: CollectionConfig = {
  slug: 'questions',
  admin: {
    useAsTitle: 'question',
    defaultColumns: ['question', 'bookTitle', 'topicHint', 'likes', 'source', 'createdAt'],
    group: 'Content',
  },
  access: {
    read: isEditorOrAdmin,  // GO-MU-08: was () => true
    create: () => true,     // anyone can create (questions are generated by AI or submitted)
    update: () => true,     // allow like updates
    delete: () => true,      // open for now (local dev)
  },
  fields: [
    {
      name: 'question',
      type: 'textarea',
      required: true,
      admin: { description: 'The study question text' },
    },
    {
      name: 'bookId',
      type: 'text',
      required: true,
      admin: { description: 'Engine book_id (e.g. "bishop_prml")' },
    },
    {
      name: 'bookTitle',
      type: 'text',
      admin: { description: 'Book title for display' },
    },
    {
      name: 'topicHint',
      type: 'text',
      admin: { description: 'Short topic label (e.g. "BM25", "Chapter 3")' },
    },
    {
      name: 'source',
      type: 'select',
      defaultValue: 'ai',
      options: [
        { label: 'AI Generated', value: 'ai' },
        { label: 'User Submitted', value: 'manual' },
      ],
    },
    {
      name: 'likes',
      type: 'number',
      defaultValue: 0,
      min: 0,
      admin: { description: 'Thumbs-up count' },
    },
    {
      name: 'category',
      type: 'text',
      admin: { description: 'Book category for filtering' },
    },
    {
      name: 'subcategory',
      type: 'text',
      admin: { description: 'Book subcategory for filtering' },
    },
    {
      name: 'questionCategory',
      type: 'text',
      admin: { description: 'AI-inferred topic classification (e.g. "Labour Market", "Housing Starts")' },
    },
    // ── QD-01: chunk traceability + reference answer ──
    {
      name: 'sourceChunkId',
      type: 'text',
      admin: { description: 'ChromaDB chunk node ID that generated this question (QD-01)' },
    },
    {
      name: 'referenceAnswer',
      type: 'textarea',
      admin: { description: 'LLM-generated reference answer for auto-evaluation (QD-01)' },
    },
    {
      name: 'datasetId',
      type: 'relationship',
      relationTo: 'question-sets',
      admin: { description: 'QuestionSet this question belongs to (QD-01)' },
    },
    {
      name: 'sourcePage',
      type: 'number',
      admin: { description: 'Source page index (0-indexed) from ChromaDB chunk metadata' },
    },
    {
      name: 'model',
      type: 'text',
      admin: { description: 'LLM model used to generate (e.g. "gpt-4o-mini", "qwen3.5:4b")' },
    },
    // ── Auto-scoring (1-5, set by LLM evaluator) ──
    {
      name: 'scoreRelevance',
      type: 'number',
      min: 1, max: 5,
      admin: { description: 'How relevant is this question to the source material (1-5)' },
    },
    {
      name: 'scoreClarity',
      type: 'number',
      min: 1, max: 5,
      admin: { description: 'How clearly written is this question (1-5)' },
    },
    {
      name: 'scoreDifficulty',
      type: 'number',
      min: 1, max: 5,
      admin: { description: 'Difficulty level (1=easy, 5=very hard)' },
    },
    {
      name: 'scoreOverall',
      type: 'number',
      min: 1, max: 5,
      admin: { description: 'Overall quality score (average of relevance + clarity)' },
    },
    // ── Depth evaluation (set by manual "Evaluate" action) ──
    {
      name: 'evalDepth',
      type: 'text',
      admin: { description: 'Question depth level: surface / understanding / synthesis' },
    },
    {
      name: 'evalScore',
      type: 'number',
      admin: { description: 'Normalized depth score (0-1)' },
    },
    {
      name: 'evalReasoning',
      type: 'textarea',
      admin: { description: 'Reasoning from the depth evaluator' },
    },
  ],
}
